---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/matrix_inversion_flowchart_290822-gv/matrix_inversion_flowchart_290822-gv.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/71114/articles/447808/master/file/figures/matrix_inversion_flowchart_290822-gv/matrix_inversion_flowchart_290822-gv.png"
